services:
  stockbit-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: stockbit-frontend
    container_name: stockbit-frontend
    restart: always
    ports:
      - 3036:80
    networks:
      - stockbit_network

networks:
  stockbit_network:
    external: true
