services:
  stockbit-backend:
    container_name: stockbit-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3028:3001'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    restart: always
    networks:
      - stockbit_network

networks:
  stockbit_network:
    driver: bridge
